# Generated by Django 4.1.4 on 2023-01-18 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0006_alter_measurement_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='measurement',
            new_name='sensor',
        ),
    ]
